### ISSUE TITLE
[공통] 이미지 첨부 컴포넌트 크기 이슈 

### ISSUE THREAD

**Issue by hijiyun** [sprint-part3-team11/taskify#36]
## 📌 기능설명
- 모바일일 때에 크기가 너무 작아서 키워야 함.

## 📌 ToDo
- [ ] 이미지 첨부 컴포넌트 크기 키우기 

## 🤔 ETC[선택]
시현님이 말씀하신 크기 외에 다른 이슈는 없는걸까요?

**Comment by sihyonn** [comment]
아예 큰 컨테이너로 감싸서 style을 받을 수 있도록 해도될거같아요!
쓰는곳에서 넘겨주도록

**Comment by sihyonn** [comment]
아! 그리고 이걸 사용하는 곳에서 imageUrl을 서버로 넘겨줘야 하는데 그걸 위한 로직이 있나용..?

**Comment by hijiyun** [comment]
> 아예 큰 컨테이너로 감싸서 style을 받을 수 있도록 해도될거같아요! 쓰는곳에서 넘겨주도록

무슨 소린지 잘 모르겠는데 자세하게 구체적으로 말씀해주실 수 있나요 
쓰는곳에서 어떤 style을 보내준다는건지 잘 모르겠어요 😭

**Comment by hijiyun** [comment]
> 아! 그리고 이걸 사용하는 곳에서 imageUrl을 서버로 넘겨줘야 하는데 그걸 위한 로직이 있나용..?



> 아! 그리고 이걸 사용하는 곳에서 imageUrl을 서버로 넘겨줘야 하는데 그걸 위한 로직이 있나용..?

이거 그냥 이미지url을 전역으로 저장한 다음에, 페이지에서 수정 또는 생성버튼을 눌렀을때 서버로 보내주는걸 생각을 했었는데, 파일 url추출 하는것도 어렵고 .... 머리가 꼬여버렸어요 지금
imageUrl을 서버로 넘겨줘야 한다는게 이미지 url을 넘겨줘야 한다는거죠 ..?
근데 파일을 콘솔로 보면 이름이랑 뭐 다 나오는데 url만 안나와요 이걸 어떻게 url을 가져와야하는지 지금 뇌정지 왔서요
